services:
  - type: web
    name: telegram-music-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7539509687:AAG-j2teWlL40G5A962tg3yuMD2nBpWsCLw
